// domains.js or config file
export const domainTopicsMap = {
  "Web Development": {
    topics: [
      "react",
      "vue",
      "angular",
      "nextjs",
      "nodejs",
      "express",
      "graphql",
      "rest-api",
      "webpack",
      "typescript",
      "progressive-web-app",
      "serverless",
    ],
  },
  "DevOps & Cloud": {
    topics: [
      "docker",
      "kubernetes",
      "terraform",
      "ansible",
      "jenkins",
      "cicd",
      "aws",
      "azure",
      "monitoring",
      "infrastructure-as-code",
      "microservices",
      "helm",
    ],
  },
  "Machine Learning & AI": {
    topics: [
      "machine-learning",
      "deep-learning",
      "tensorflow",
      "pytorch",
      "neural-networks",
      "computer-vision",
      "nlp",
      "reinforcement-learning",
      "scikit-learn",
      "keras",
      "transformers",
      "mlops",
    ],
  },
  "Blockchain & Web3": {
    topics: [
      "blockchain",
      "ethereum",
      "bitcoin",
      "smart-contracts",
      "solidity",
      "web3",
      "defi",
      "nft",
      "dapp",
      "cryptography",
      "polygon",
      "layer2",
    ],
  },
  "Systems Programming": {
    topics: [
      "operating-systems",
      "systems-programming",
      "embedded-systems",
      "kernel",
      "compilers",
      "memory-management",
      "concurrency",
      "networking",
      "low-level",
      "assembly",
      "performance",
      "real-time",
    ],
  },
  "Mobile Development": {
    topics: [
      "android",
      "ios",
      "react-native",
      "flutter",
      "kotlin",
      "swift",
      "mobile-app",
      "jetpack-compose",
      "swiftui",
      "cross-platform",
      "pwa",
      "expo",
    ],
  },
  Cybersecurity: {
    topics: [
      "security",
      "cybersecurity",
      "penetration-testing",
      "cryptography",
      "vulnerability",
      "ethical-hacking",
      "infosec",
      "malware-analysis",
      "reverse-engineering",
      "network-security",
      "osint",
      "ctf",
    ],
  },
  "Game Development": {
    topics: [
      "game-development",
      "gamedev",
      "unity",
      "unreal-engine",
      "godot",
      "game-engine",
      "3d",
      "2d",
      "blender",
      "graphics",
      "physics",
      "shader",
      "multiplayer",
    ],
  },
  "Data Science & Analytics": {
    topics: [
      "data-science",
      "data-analysis",
      "data-visualization",
      "pandas",
      "numpy",
      "jupyter",
      "big-data",
      "analytics",
      "statistics",
      "data-engineering",
      "etl",
      "spark",
    ],
  },
  "IoT & Embedded": {
    topics: [
      "iot",
      "embedded",
      "arduino",
      "raspberry-pi",
      "esp32",
      "mqtt",
      "sensors",
      "firmware",
      "hardware",
      "robotics",
      "microcontroller",
      "home-automation",
    ],
  },
  "Backend & Databases": {
    topics: [
      "backend",
      "api",
      "rest",
      "graphql",
      "database",
      "postgresql",
      "mongodb",
      "redis",
      "microservices",
      "serverless",
      "authentication",
      "orm",
    ],
  },
  "Cloud Native": {
    topics: [
      "cloud-native",
      "kubernetes",
      "docker",
      "service-mesh",
      "istio",
      "serverless",
      "containers",
      "helm",
      "observability",
      "distributed-systems",
      "grpc",
      "cncf",
    ],
  },
};
